### ISSUE TITLE
Purpose vs. naming of this library

### ISSUE THREAD

**Issue by k00ni** [sweetrdf/quickRdf#2]
If the purpose of this library is to only provide implementations for quickrdf/rdfInterfaces, it should be named differently. `quickrdf/quickrdf` is not good anymore, because it seems that it may use/reference all other libraries from `quickrdf` organization (much like `symfony/symfony` does). 

I propose that we rename it to something like `standardImplementations`.

**Comment by zozlak** [comment]
Don't wanna be rude but I was first with the name. Please invent a new organization name if you want to avoid this situation.

**Comment by k00ni** [comment]
No problem, I renamed the organization.
